split_type = {
    'EQUAL': 'EQUAL',
    'PERCENT': 'PERCENT',
    'EXACT': 'EXACT'
}


valid_actions = {
    'ADD_EXPENSE': 'ADD_EXPENSE',
    'SETTLE_UP': 'SETTLE_UP'
}

output_messages = {
    'INVALID_SPLIT_TYPE': 'INVALID_SPLIT_TYPE',
    'INVALID_ACTION': 'INVALID_ACTION',
    'INVALID_PERCENT_SPLIT': 'INVALID_PERCENT_SPLIT',
    'INVALID_EXACT_SPLIT': 'INVALID_EXACT_SPLIT'
}